import { MATERIAL_CATALOG_SEED, materialCatalogById } from "@dynecho/catalogs";
import type { MaterialDefinition } from "@dynecho/shared";

const MATERIAL_ID_ALIASES: Record<string, string> = {
  aac_d700: "ytong_aac_d700",
  aac_g5_800: "ytong_g5_800",
  cement_render: "cement_plaster",
  celcon_dense_finish: "celcon_dense_plaster",
  celcon_dense_plaster_13: "celcon_dense_plaster",
  celcon_high: "celcon_high_strength",
  celcon_lightweight_finish: "celcon_lwt_plaster",
  celcon_lightweight_plaster_13: "celcon_lwt_plaster",
  celcon_lwt_finish: "celcon_lwt_plaster",
  celcon_lwt_plaster_13: "celcon_lwt_plaster",
  celcon_solar: "celcon_solar_grade",
  celcon_standard: "celcon_standard_grade",
  dense_gypsum_plaster: "dense_plaster",
  db: "diamond_board",
  db_board: "diamond_board",
  diamant: "diamond_board",
  diamant_board: "diamond_board",
  diamond: "diamond_board",
  engineered_timber_structural: "timber_joist_floor",
  eps_acoustic_underlay: "eps_underlay",
  eps_70: "eps_70_insulation_board",
  eps_100: "eps_100_insulation_board",
  eps_150: "eps_150_insulation_board",
  fermacell: "fermacell_gypsum_fibreboard_1150",
  fermacell_board: "fermacell_gypsum_fibreboard_1150",
  fermacell_gypsum_fibreboard: "fermacell_gypsum_fibreboard_1150",
  fire_board: "firestop_board",
  fiber_cement: "fiber_cement_board_1290",
  fiber_cement_board: "fiber_cement_board_1290",
  gypsum: "gypsum_board",
  gypsum_fiberboard: "dry_floating_gypsum_fiberboard",
  gypsum_fibreboard: "fermacell_gypsum_fibreboard_1150",
  gyproc_fireline: "gyproc_fireline_12_5",
  gyproc_fireline_12_5mm: "gyproc_fireline_12_5",
  gyproc_habito: "gyproc_habito_12_5",
  gyproc_habito_12_5mm: "gyproc_habito_12_5",
  gyproc_soundbloc: "gyproc_soundbloc_12_5",
  gyproc_soundbloc_12_5mm: "gyproc_soundbloc_12_5",
  gyproc_soundbloc_15mm: "gyproc_soundbloc_15",
  gyproc_wallboard_ten: "gyproc_wallboard_ten_12_5",
  habito: "gyproc_habito_12_5",
  heluz_14_brousena: "heluz_14_brushed",
  heluz_aku_11_5: "heluz_aku_115",
  heluz_aku_20: "heluz_aku_200_p15",
  heluz_aku_30_33_3: "heluz_aku_300_333_p20",
  heluz_aku_30_333: "heluz_aku_300_333_p20",
  lime_cement_plaster: "lime_cement_plaster_1700",
  lightweight_render: "lightweight_plaster",
  mw_t_10_impact_layer: "generic_resilient_underlay",
  mw_t_40_impact_layer: "mw_t_impact_layer_s40",
  open_web_steel_joist: "open_web_steel_floor",
  osb_3: "osb_3_640",
  pir: "pir_board_30",
  pir_board: "pir_board_30",
  particleboard_flooring: "inex_floor_panel",
  plaster_cement: "cement_plaster",
  plaster_dense: "dense_plaster",
  plaster_lightweight: "lightweight_plaster",
  plaster_lime_cement_1300: "lime_cement_plaster_1300",
  plaster_lime_cement_1700: "lime_cement_plaster_1700",
  plaster_lime_cement_1780: "lime_cement_plaster_1780",
  porotherm_100: "porotherm_pls_100",
  porotherm_140: "porotherm_pls_140",
  porotherm_190: "porotherm_pls_190",
  porotherm_clay_block_100: "porotherm_pls_100",
  porotherm_clay_block_140: "porotherm_pls_140",
  porotherm_clay_block_190: "porotherm_pls_190",
  pumice_bims_block: "pumice_block",
  rubber_sheet: "generic_resilient_underlay",
  security: "security_board",
  skim_coat_plaster: "skim_plaster",
  silicate_block: "silka_cs_block",
  silent: "silentboard",
  silka_block: "silka_cs_block",
  sand_lime_block: "silka_cs_block",
  calcium_silicate_block: "silka_cs_block",
  solid_wood: "timber_joist_floor",
  soundbloc_board: "acoustic_gypsum_board",
  xps: "xps_foam_board_40",
  xps_board: "xps_foam_board_40",
  xps_foam: "xps_foam_board_40",
  steel_deck_composite: "composite_steel_deck",
  wallboard_ten: "gyproc_wallboard_ten_12_5",
  knauf_acoustic_roll: "knauf_acoustic_roll_034",
  knauf_pro_hd: "knauf_pro_hd_12_5",
  knauf_soundshield_plus: "knauf_soundshield_plus_12_5",
  knauf_soundshield_plus_12_5mm: "knauf_soundshield_plus_12_5",
  knauf_soundshield_plus_15mm: "knauf_soundshield_plus_15",
  melamine_foam: "basotect_melamine_foam",
  basotect: "basotect_melamine_foam",
  cork_underlay: "cork_underlay_184",
  quietcork: "cork_underlay_184",
  quietrock510: "quietrock_510",
  quietrock530: "quietrock_530",
  quietrock_510_panel: "quietrock_510",
  quietrock_530_panel: "quietrock_530",
  regupol_comfort8: "regupol_comfort_8",
  regupol_comfort12: "regupol_comfort_12",
  regupol_sound12: "regupol_sound_12",
  regupol_sound15: "regupol_sound_15",
  regupol_sound17: "regupol_sound_17",
  regupol_sound47: "regupol_sound_47",
  regupol_sound_and_drain22: "regupol_sound_and_drain_22",
  scan_825: "scanrubber_825_underlay",
  scan_underlay_825: "scanrubber_825_underlay",
  soundbloc_12_5: "gyproc_soundbloc_12_5",
  soundbloc_15: "gyproc_soundbloc_15",
  stora_enso_clt: "stora_enso_clt_490",
  tecsound35: "tecsound_sy_35",
  tecsound50: "tecsound_sy_50",
  tecsound70: "tecsound_sy_70",
  tecsound100: "tecsound_sy_100",
  tecsound_sy35: "tecsound_sy_35",
  tecsound_sy50: "tecsound_sy_50",
  tecsound_sy70: "tecsound_sy_70",
  tecsound_sy100: "tecsound_sy_100",
  oc703: "owens_corning_703",
  oc705: "owens_corning_705",
  owens_corning_703_board: "owens_corning_703",
  owens_corning_705_board: "owens_corning_705",
  rockwool_afb: "rockwool_afb_40",
  rockwool_afb_40kg: "rockwool_afb_40",
  rwa45: "rockwool_rwa45",
  rockwool_rwa_45: "rockwool_rwa45",
  rw3: "rockwool_rw3",
  rw4: "rockwool_rw4",
  rw5: "rockwool_rw5",
  rw6: "rockwool_rw6",
  ytong_d700: "ytong_aac_d700",
  ytong_g4_600: "ytong_separatiepaneel_aac_4_600",
  ytong_g2_300: "ytong_massief_g2_300",
  ytong_g5_800_panel: "ytong_g5_800",
  ytong_aac_4_600: "ytong_separatiepaneel_aac_4_600",
  ytong_aac_5_750: "ytong_separatiepaneel_aac_5_750",
  ytong_block_g4_600: "ytong_cellenbetonblok_g4_600",
  ytong_block_g5_800: "ytong_cellenbetonblok_g5_800",
  ytong_cellenbetonblok_4_600: "ytong_cellenbetonblok_g4_600",
  hh_celcon_solar: "hh_celcon_solar_460",
  hh_celcon_standard: "hh_celcon_standard_600",
  hh_celcon_high_strength: "hh_celcon_high_strength_730",
  ytong_cellenbetonblok_5_800: "ytong_cellenbetonblok_g5_800",
  ytong_separatiepaneel_4_600: "ytong_separatiepaneel_aac_4_600",
  ytong_separatiepaneel_5_750: "ytong_separatiepaneel_aac_5_750"
};

export function getDefaultMaterialCatalog(): readonly MaterialDefinition[] {
  return MATERIAL_CATALOG_SEED;
}

export function resolveMaterial(
  materialId: string,
  catalog: readonly MaterialDefinition[] = MATERIAL_CATALOG_SEED
): MaterialDefinition {
  const canonicalMaterialId = MATERIAL_ID_ALIASES[materialId] ?? materialId;

  if (catalog === MATERIAL_CATALOG_SEED && materialCatalogById[canonicalMaterialId]) {
    return materialCatalogById[canonicalMaterialId];
  }

  const hit = catalog.find((entry) => entry.id === canonicalMaterialId);
  if (!hit) {
    throw new Error(`Unknown material: ${materialId}`);
  }

  return hit;
}
