import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import { execInUpstreamRepo, readUpstreamSnapshot } from "./acoustic2";
import { runUpstreamJson } from "./json";

type InventoryCoreSummary = {
  calculators: Array<{ id: string; label: string }>;
  coreExports: string[];
  materialCount: number;
};

function main() {
  const explicitPath = process.argv[2];
  const snapshot = readUpstreamSnapshot(explicitPath);
  const trackedFiles = execInUpstreamRepo("git", ["ls-files"], explicitPath)
    .split("\n")
    .filter(Boolean);
  const coreSummary = runUpstreamJson<InventoryCoreSummary>(
    `
      const core = require("./core.js");
      console.log(JSON.stringify({
        calculators: Array.isArray(core.CALCULATORS)
          ? core.CALCULATORS.map((entry) => ({ id: entry.id, label: entry.label }))
          : [],
        coreExports: Object.keys(core).sort(),
        materialCount: Array.isArray(core.BASE_MATERIALS) ? core.BASE_MATERIALS.length : 0
      }));
    `,
    explicitPath
  );

  const report = {
    core: {
      calculatorCount: coreSummary.calculators.length,
      calculators: coreSummary.calculators,
      exportCount: coreSummary.coreExports.length,
      materialCount: coreSummary.materialCount
    },
    focus: {
      benchmarkFileCount: trackedFiles.filter((filePath) => /^tools\/reference-benchmarks.*\.json$/.test(filePath)).length,
      impactOrLnwTestCount: trackedFiles.filter(
        (filePath) => filePath.startsWith("tests/") && /(impact|lnw|formula-notes)/i.test(filePath)
      ).length
    },
    generatedAt: new Date().toISOString(),
    trackedCounts: {
      all: trackedFiles.length,
      tests: trackedFiles.filter((filePath) => filePath.startsWith("tests/")).length,
      tools: trackedFiles.filter((filePath) => filePath.startsWith("tools/")).length
    },
    upstream: {
      branch: snapshot.branch,
      dirtyCount: snapshot.statusLines.length,
      head: snapshot.head,
      headShort: snapshot.head.slice(0, 7),
      path: snapshot.path,
      statusLines: snapshot.statusLines,
      watchLines: snapshot.statusLines
        .filter((line) => /(impact|lnw|floor-system|catalog|benchmark|core\.js|app\.js)/i.test(line))
        .slice(0, 12)
    }
  };

  const targetDir = path.resolve(process.cwd(), "apps/web/features/workbench");
  const filePath = path.join(targetDir, "generated-upstream-snapshot.ts");
  const contents = `/* This file is generated by tools/upstream/refresh-workbench-snapshot.ts. */\nexport const GENERATED_UPSTREAM_SNAPSHOT = ${JSON.stringify(report, null, 2)} as const;\n`;

  mkdirSync(targetDir, { recursive: true });
  writeFileSync(filePath, contents, "utf8");

  console.log(filePath);
}

main();
